#Aqui se configuran los contenedores
services:
  database:
    image: mysql:8
    container_name: adj-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adj-demo
    ports:
      - "3307:3306"
    networks:
      - adj-net
    volumes:
      - adj-volume:/var/lib/mysql

  frontend:
    image: client:v1.0
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /adj-api
        API_PROTOCOL: https
    container_name: adj-client
    ports:
      - "3000:80"
    networks:
      - adj-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database

  backend:
    image: server:v1.0
    build:
      context: ./server
    container_name: adj-server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: adj-demo
      DB_USER: root
      DB_PASSWORD: root
      SERVER_SSL_ENABLE: true
      SERVER_SSL_KEYSTORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_KEYSTORE_PASS: changeit
    ports:
      - "8081:8080"
    networks:
      - adj-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend

#Aqui se configuran las redes donde se comunican los contenedores
#Para crear la red es 
#docker network create --driver bridge adj-net
networks:
  adj-net:
    external: true

#Aqui se configuran los volumenes que ocupan los contenedores
#docker volume create adj-volume
volumes:
  adj-volume:
    external: true
  certbot-conf:
    external: true